version: '3.9'
services: 
  mongodb:
    container_name: db-accounts
    image: mongo
    hostname: host-bank
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hrevilla
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data-accounts:/data/db
    networks:
      - bank

volumes:
  data-accounts:
    name: data-accounts

networks:
  bank:
    name: bank