version: '3.9'
services: 
  mongodb:
    container_name: db-accounts
    image: mongo
    hostname: host-bank
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: hrevilla
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - data-mongodb:/var/lib/accountsdb
      - logs-mongodb:/var/log/accountsdb/
    networks:
      - bank

volumes:
  data-mongodb:
    name: accountsdb
  logs-mongodb:
    name: accountsdb

networks:
  bank:
    name: bank